CREATE TABLE user (
 id int NOT NULL AUTO_INCREMENT,
 uuid VARCHAR(255),
 handle_name VARCHAR(255),
 display_name VARCHAR(255),
 password VARCHAR(255),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id)
);